# Generated by Django 4.0 on 2022-04-25 08:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='id',
            fields=[
                ('loginid', models.EmailField(default='', max_length=20, primary_key=True, serialize=False)),
                ('password', models.TextField(default='', max_length=20)),
                ('name', models.TextField(default='', max_length=20)),
                ('emailid', models.EmailField(default='', max_length=20)),
                ('cellno', models.IntegerField(default=0)),
            ],
        ),
    ]
