# Generated by Django 4.0 on 2022-04-25 08:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='id',
            name='name',
            field=models.EmailField(default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='id',
            name='password',
            field=models.EmailField(default='', max_length=20),
        ),
    ]
