# Generated by Django 4.0 on 2022-04-25 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_alter_id_name_alter_id_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='id',
            name='emailid',
            field=models.EmailField(default='', max_length=50),
        ),
    ]
